### ISSUE TITLE
flickcurl error - Method flickr.oauth.access_token failed with error 0 - (null) (HTTP 401)

### ISSUE THREAD

**Issue by lboullo0** [patrickjennings/FlickrMS#4]
I followed the installation guide and after enter the 9 digit code I get the error:
flickcurl error - Method flickr.oauth.access_token failed with error 0 - (null) (HTTP 401)

(I'm running kubuntu 16.04)

**Comment by patrickjennings** [comment]
This seems to be related to [issue #26](https://github.com/dajobe/flickcurl/issues/26) in the Flickcurl library which references a bug I reported and was fixed by the developer over a year ago. Unfortunately, I don't think there has been an official release of the library since it was fixed. If you installed Flickcurl from your package manager (which I would have too...), I believe that you will run into this issue.

You can get around this issue by compiling and installing the latest Flickcurl code from the [Github repository](https://github.com/dajobe/flickcurl) and trying again.

You can also try following the directions for creating the ~/.flickcurl.conf file yourself using the flickcurl utility: [Register application to get Client Key and Client Secret](http://librdf.org/flickcurl/api/flickcurl-auth-register.html) and [Getting Authentication Token from Client Key and Client Secret](http://librdf.org/flickcurl/api/flickcurl-auth-authenticate.html). This will get you around the problem you are seeing.

Thanks for drawing my attention to this issue. I thought it would have been fixed upstream by now.

**Comment by lboullo0** [comment]
Thank you for your quick reply.

I tried cloning Flickcurl code and compiling it but the error persist. I also tried with http://download.dajobe.org/flickcurl/flickcurl-1.26.tar.gz and I get the same error.
Then I follow the links you provide to create ~/.flickcurl.conf and that worked.
Thank you.
